config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/restaurants', to: 'restaurants#index', as: 'restaurants'
  post '/restaurants', to: 'restaurants#create'
  get '/restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  get '/restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  put '/restaurants/:id', to: 'restaurants#update'
  patch '/restaurants/:id', to: 'restaurants#update'
  get '/restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'
  root 'restaurants#index'
  post '/reviews', to: 'reviews#create', as: 'review'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  validates :title, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :food_type, presence: true

  has_many :reviews
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  load_and_authorize_resource

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
      end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  private

  def restaurant_params
    params.permit(:title, :address, :description, :food_type)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(review_params)
    redirect_to restaurant_path(@restaurant.id)
  end

  private

  def review_params
    params.permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
  <div class="navbar-right hidden-xs hidden-sm">
    <a href="/restaurants/new" class="navbar-item navbar-link">New Restaurant</a>
    <a href="/restaurants" class="navbar-item navbar-link">Restaurants</a>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails-Restaurant-Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <div id="navbar">
  <ul class="nav navbar-nav">
    <li><%= link_to 'Home', root_path %></li>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to 'Log In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</div>
<% flash.each do |key, value| %>
  <%= value %>
<% end %>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<form action="<%= restaurant_path(params[:id]) %>" method="POST" >
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <input type="hidden" name="_method" value="patch" />

    <label for="title">Title</label>
    <input type="text" name="title" id="title" value="<%= @restaurant.title %>"/>

    <label for="address">Address</label>
    <input type="text" name="address" name="address" id="address" value="<%= @restaurant.address %>"/>

    <label>Description</label>
    <input type="textarea" name="description" id="description" value="<%= @restaurant.description %>" />

    <label for="food_type">Food type</label>
    <input type="text" name="food_type" id="food_type"  value="<%= @restaurant.food_type %>"/>

    <input type="submit" value="Update" />
</form>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
    <% @restaurants.each_with_index do |restaurant, index| %>
        <li>
            <%= restaurant.title %> - <%= restaurant.food_type %> 
            <%= link_to "show", restaurant_path(restaurant.id) %>
            <% if can? :update, restaurant %>
             <%= link_to "edit", edit_restaurant_path(restaurant.id) %>
             <% end %>
            <p>Reviews: <%= restaurant.reviews.count %></p>
        </li>
    <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create A New Restaurant</h1>

<form action="<%= restaurants_path %>" method="POST" >
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <% if @restaurant.errors.any? %>
    <div id="error_explanation">
        <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this article from being saved:
        </h2>
        <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    
    <label for="title">Title</label>
    <input type="text" name="title" id="title"/>

    <label for="address">Address</label>
    <input type="text" name="address" name="address" id="address"/>

    <label>Description</label>
    <input type="textarea" name="description" id="description" />

    <label for="food_type">Food type</label>
    <input type="text" name="food_type" id="food_type" />

    <input type="submit" value="Create" />
</form>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.title %></h2>

<h3>Food Type</h3>
<p><%= @restaurant.food_type %></p>

<h3>Address</h3>
<p><%= @restaurant.address %></p>

<h3>Description</h3>
<p><%= @restaurant.description %></p>

<h3>Reviews</h3>
<ul>
    <% @restaurant.reviews.each do |review| %>
        <li>
            <p><%= review.title %> - <%= review.rating %> </p>
            <p><%= review.content %></p>
        </li>
    <% end %>
</ul>
<h3>Add a Review</h3>

<form action="<%= review_path %>" method="POST" >
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
    <input type="hidden" value="<%= @restaurant.id %>" name="restaurant_id" />

    <label for="title">Title</label>
    <input type="text" name="title" id="title"/>

    <label for="content">Content</label>
    <input type="text" name="content" id="content"/>

    <label for="rating">Rating</label>
    <input type="text" name="rating" id="rating" />

    <input type="submit" value="Create" />
</form>

<%= link_to "Back", :back %>